language: R
sudo: no
cache: packages
r_github_packages: krlmlr/travis@develop
after_success:
  - R -e "travis::deploy(tasks = c('travis::task_install_ssh_keys()'))"
  - ssh -vvv git@github.com
  - git remote remove origin
  - git remote add origin git@github.com:${TRAVIS_REPO_SLUG}
  - git checkout ${TRAVIS_BRANCH}
  - git config user.email "$(git show --format="%ae" | head -n 1)"
  - git config user.name "$(git show --format="%an" | head -n 1)"
  - git commit -m "test [ci skip]" --allow-empty
  - git push -u origin HEAD
